spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=${PG_USER:dcql}
spring.datasource.password=${PG_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Enable the Hibernate Statistics API
spring.jpa.properties.hibernate.generate_statistics=true

# Optional: reduce noise from unrelated logs
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.orm.jdbc.bind=ERROR
logging.level.org.hibernate.stat=ERROR
